import type {GameEvent,Player} from '../../shared/replay';
export type EventFilter='All'|'Kills'|'Respawns'|'Objectives'|'Structures';
export const getEventReviewStart=(event:GameEvent)=>Math.max(0,event.timestamp-(event.type==='OBJECTIVE_KILL'?10:event.type==='CHAMPION_RESPAWN'?3:8));
export function eventInvolves(event:GameEvent,id:number){return event.type==='CHAMPION_KILL' ? event.victimPlayerId===id||event.killerPlayerId===id||Boolean(event.assistingPlayerIds?.includes(id)) : event.type==='CHAMPION_RESPAWN'?event.playerId===id:event.type==='OBJECTIVE_KILL'&&event.killerPlayerId===id;}
export function filterEvents(events:readonly GameEvent[],filter:EventFilter,player?:number|null){return events.filter(e=>(filter==='All'||e.type===({Kills:'CHAMPION_KILL',Respawns:'CHAMPION_RESPAWN',Objectives:'OBJECTIVE_KILL',Structures:'STRUCTURE_DESTROYED'} as const)[filter])&&(player==null||eventInvolves(e,player)));}
export function eventUpperBound(events:readonly GameEvent[],time:number){let lo=0,hi=events.length;while(lo<hi){const mid=(lo+hi)>>>1;if(events[mid].timestamp<=time)lo=mid+1;else hi=mid;}return lo;}
/** Sorted input, inclusive interval; O(log n + number of matches). */
export function findEventsNearTimestamp(events:readonly GameEvent[],time:number,seconds=3){let first=eventUpperBound(events,time-seconds);while(first>0&&events[first-1].timestamp===time-seconds)first--;return events.slice(first,eventUpperBound(events,time));}
export function indexEvents(events:readonly GameEvent[],players:readonly Player[]){const sorted=[...events].sort((a,b)=>a.timestamp-b.timestamp||a.id.localeCompare(b.id));return {sorted,byId:new Map(sorted.map(e=>[e.id,e])),byPlayer:new Map(players.map(p=>[p.id,sorted.filter(e=>eventInvolves(e,p.id))]))};}
export function eventLabel(event:GameEvent,players:readonly Player[]){const name=(id?:number)=>players.find(p=>p.id===id)?.championName??'Non-player source';if(event.type==='CHAMPION_KILL')return `${name(event.killerPlayerId)} → ${name(event.victimPlayerId)}`;if(event.type==='CHAMPION_RESPAWN')return `${name(event.playerId)} respawned`;if(event.type==='OBJECTIVE_KILL')return `${event.killerTeam??'Unknown team'} killed ${event.objective.replaceAll('_',' ')}`;return `${event.destroyedTeam} ${event.structure.toLowerCase()} destroyed`;}
export function eventDetails(event:GameEvent,players:readonly Player[]){if(event.type!=='CHAMPION_KILL')return eventLabel(event,players);return `${eventLabel(event,players)}\nAssists: ${event.assistingPlayerIds ? event.assistingPlayerIds.map(id=>players.find(p=>p.id===id)?.championName??id).join(', ')||'None' : 'not decoded'}`;}
export function eventCategory(e:GameEvent){return e.type==='CHAMPION_KILL'?'kill':e.type==='CHAMPION_RESPAWN'?'respawn':e.type==='OBJECTIVE_KILL'?e.objective.toLowerCase():e.structure.toLowerCase();}
export function currentScore(events:readonly GameEvent[],time:number,player:number){let kills=0,deaths=0;const end=eventUpperBound(events,time);for(let i=0;i<end;i++){const e=events[i];if(e.type==='CHAMPION_KILL'){if(e.killerPlayerId===player)kills++;if(e.victimPlayerId===player)deaths++;}}return {kills,deaths};}
